# This is a basic workflow to help you get started with Actions

name: Hexo Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install Dependencies and Hexo
        run: |
          git config --global user.email "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          git config --global user.name "github.actor"
          sed -i "s/__GITHUB_TOKEN__/${{ secrets.DEPLOY_TOKEN }}/" _config.yml
          npm install
          npm install -g hexo-cli

      - name: Deploy Hexo Application
        run: |
          hexo clean
          hexo deploy --generate
